### ISSUE TITLE
Cannot find module error when trying to run

### ISSUE THREAD

**Issue by shockyrow** [ndom91/newtelco-tab#4]
I followed the steps in the README.md, but something seems to be missing because after I try to open the page I see `Internal Server Error` and following error in the terminal:
```
Error: Cannot find module '/app/.next/fallback-build-manifest.json'
Require stack:
- /app/node_modules/next/dist/server/load-components.js
- /app/node_modules/next/dist/server/next-server.js
- /app/node_modules/next/dist/server/next.js
- /app/node_modules/next/dist/server/lib/start-server.js
- /app/node_modules/next/dist/cli/next-dev.js
- /app/node_modules/next/dist/lib/commands.js
- /app/node_modules/next/dist/bin/next
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:985:15)
    at Function.mod._resolveFilename (/app/node_modules/next/dist/build/webpack/require-hook.js:27:32)
    at Function.mod._resolveFilename (/app/node_modules/next/dist/build/webpack/require-hook.js:27:32)
    at Function.mod._resolveFilename (/app/node_modules/next/dist/build/webpack/require-hook.js:27:32)
    at Function.Module._load (node:internal/modules/cjs/loader:833:27)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.loadDefaultErrorComponents (/app/node_modules/next/dist/server/load-components.js:22:24)
    at DevServer.getFallbackErrorComponents (/app/node_modules/next/dist/server/dev/next-dev-server.js:1008:43)
    at async DevServer.renderErrorToResponse (/app/node_modules/next/dist/server/base-server.js:1111:40)
    at async pipe.req.req (/app/node_modules/next/dist/server/base-server.js:1033:30)
    at async DevServer.pipe (/app/node_modules/next/dist/server/base-server.js:387:25)
    at async DevServer.run (/app/node_modules/next/dist/server/dev/next-dev-server.js:715:24)
    at async DevServer.handleRequest (/app/node_modules/next/dist/server/base-server.js:303:20) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/app/node_modules/next/dist/server/load-components.js',
    '/app/node_modules/next/dist/server/next-server.js',
    '/app/node_modules/next/dist/server/next.js',
    '/app/node_modules/next/dist/server/lib/start-server.js',
    '/app/node_modules/next/dist/cli/next-dev.js',
    '/app/node_modules/next/dist/lib/commands.js',
    '/app/node_modules/next/dist/bin/next'
  ]
}```

**Comment by Woahai321** [comment]
same

**Comment by mattish91** [comment]
Valid issue, same for me.
